# Generated by Django 5.1.2 on 2024-11-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_desempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('TRANCADO', 'Trancado'), ('FORMADO', 'Formado')], default='ATIVO', max_length=8),
        ),
    ]
