# Generated by Django 5.1.2 on 2024-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='semestre_atual',
            field=models.IntegerField(default=1),
        ),
    ]
