# Generated by Django 5.1.2 on 2024-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aluno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
